# Generated by Django 4.2.20 on 2025-05-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreatedalbum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/albums/'),
        ),
    ]
