# Generated by Django 4.2.20 on 2025-05-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_genres_delete_artistgenre'),
        ('user', '0002_usercreatedalbum_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreatedalbum',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.artist'),
        ),
    ]
