# Generated by Django 4.2.20 on 2025-05-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercreatedalbum_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreatedalbum',
            name='artist',
        ),
    ]
