# Generated by Django 4.2.20 on 2025-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='preview_url',
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/albums/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/artists/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
