# Generated by Django 4.2.20 on 2025-04-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_track_preview_url_alter_album_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/tracks/'),
        ),
    ]
