# Generated by Django 4.2.20 on 2025-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='music.genre'),
        ),
        migrations.DeleteModel(
            name='ArtistGenre',
        ),
    ]
